### ISSUE TITLE
How to use Head Stage Dongle with open-ephys GUI?

### ISSUE THREAD

**Issue by Qifan94** [open-ephys-GUI-binaries/open-ephys#2]
Hi, 
I am trying to use open-ephys to record from Neuropixels probes. For the time being, I want to use Head Stage Dongle to test the head stage without probes. Though there is a description in the Neuropixel user manual `the HS tests will be integrated in the application software (Open Ephys, SpikeGLX)` [https://docs.wixstatic.com/ugd/832f20_c1bc99abc9b1416ebe3f34d9a0cbca21.pdf](url) (Page 18).

In the manual of open-ephys, [https://open-ephys.atlassian.net/wiki/spaces/OEW/pages/963280903/Neuropix-PXI](url), there is only a section named `Built-in self tests` , which seems to only could work with probe connected. 

My question is can open-ephys do the test with Head Stage Dongle?

Thanks!

**Comment by jsiegle** [comment]
We haven't added support for the headstage dongle yet. That's the next thing on our to-do list after we finish the NIDAQ plugin for auxiliary analog and digital inputs, which should be ready in the next week or so. I just opened an issue for it here: https://github.com/open-ephys/neuropixels-pxi/issues/8

**Comment by Qifan94** [comment]
Thanks!

**Comment by medengineer** [comment]
Added w commit 6624312

**Comment by mreisenb** [comment]
Hi, I saw this was resolved a while ago, but I just installed open ephys last week to set up our neuropixel system but I cant seem to get it to recognize the dongle

**Comment by jsiegle** [comment]
If your Neuropixels PXI card has the latest firmware on it, then it won't be able to connect the dongle. This is due to an issue with the Neuropixels API.

In general, we haven't found the dongle to be useful for diagnosing problems with headstages. If you're having issues acquiring data, let us know and we can help you troubleshoot!
