### ISSUE TITLE
NI-DAQmx dll loading error

### ISSUE THREAD

**Issue by ZeitgeberH** [open-ephys-GUI-binaries/open-ephys#3]
Hi,
The console print the following error when starting:
"Loading Plugin: NI-DAQmx... ..\..\Source\Processors\PluginManager\PluginManager.cpp:181: Failed to load plugin DLL: DLL Error 0x5
 DLL Load FAILED"

I have NIDAQmx 18.5 installed.

**Comment by medengineer** [comment]
Hi, 
Can you try upgrading to NIDAQmx 19.0?

**Comment by ZeitgeberH** [comment]
> Hi,
> Can you try upgrading to NIDAQmx 19.0?

I installed NIDAQmx 19.1. And it works! Thanks!
