### ISSUE TITLE
enclustra windows 10 drivers?

### ISSUE THREAD

**Issue by danieljdenman** [open-ephys-GUI-binaries/open-ephys#4]
are the drivers in the Drivers>Enclustra folder supposed to work for windows 10? i tried to manually install them in Device Manager, but it didn't work. Downloading the windows 10 drivers bill has on the spikeGLX website (https://billkarsh.github.io/SpikeGLX/#pxi-enclustra-drivers) and manually installing them did work, and allowed me to connect to a probe.

**Comment by jsiegle** [comment]
We've only tested tested it on Windows 10, so I'd expect it to work. But I think we should have a separate folder for the 7 & 10 versions, like SpikeGLX. @medengineer, can you take care of this?

**Comment by medengineer** [comment]
Added w/ a5abd0f
