### ISSUE TITLE
PC build for Neuropixel acquistion

### ISSUE THREAD

**Issue by Hankslab-ABG** [open-ephys-GUI-binaries/open-ephys#8]
Greetings,

My apologies if this question is best directed elsewhere, please let me know a more appropriate location if that's the case.

We're setting up our neuropixel infrastructure and buying the necessary equipment, but we've been struggling to figure out a PC build that will meet our needs and budget. Have other users reported whether a dual-CPU PC is actually necessary or can one get away with a single-socket setup using a newer i7 or i9x intel CPU? Likely we won't be using more than 2 probes for awhile, but we'd like to be able to purchase a system that will suit our needs in the long term.

The SpikeGLX "minimum requirements" make it seem like one could get away with a single-core setup, but I know that there are difference in the programs. Any help you could provide would be greatly appreciated. We're really excited to get started with these. :)

Best,

-Adam

**Comment by jsiegle** [comment]
Hi Adam, a dual-CPU setup is definitely not necessary...a newer i7 or i9 should be totally fine.

**Comment by Hankslab-ABG** [comment]
Hey Josh,

Thanks for getting back to me. Following up on that, is AVX-512 capability beneficial for acquisition/visualization (i.e. core x-series such as the i9-9900x) or does that not come into play?

Thanks,

-Adam

**Comment by jsiegle** [comment]
We haven't done any optimization to take advantage of that instruction set, so it's unlikely to help.

**Comment by Hankslab-ABG** [comment]
I see. Is there a chance that a future build might leverage that capability or is it too hard to say?

**Comment by jsiegle** [comment]
It's certainly possible, but we're not currently planning on it.

**Comment by Hankslab-ABG** [comment]
That's good to know. I think we have all the info we need. Thanks very much for all your help Josh. We're excited to get this rig built and fired up. We'll let you know how things go with our specific build so other users can benefit from the additional data.

Best,

-Adam
